name: Publish to NPM

on:
  push:
    branches:
      - master

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    permissions:
      contents: read

    name: CI

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20', '22', '24']

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          package-manager-cache: false

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run CI
        run: npm run ci

  publish:
    needs:
      - ci
    if: github.repository == 'kernie66/homebridge-telldus-too'
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          package-manager-cache: false

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Create Release or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
          NPM_TOKEN: "" # Workaround. See https://github.com/changesets/changesets/issues/1152#issuecomment-3190884868